### ISSUE TITLE
Support MongoDB as a storage provider

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#103]
We currently use webtask storage to persist groups, roles and permissions. Support these additional providers to go beyond the storage limit.

**Comment by girishgoudapatil** [comment]
Any updates on this one please?

**Comment by nashton** [comment]
I added a pull request here: https://github.com/auth0/auth0-authorization-extension/pull/208
There has been a couple before, but they were not merged.

**Comment by aarongodin** [comment]
Based on the response in #208, I'm closing this as we are not developing features for this extension.
