### ISSUE TITLE
Documentation for v2

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#108]
The documentation should cover:

- The fact that we dropped support for applications
- What are groups + group mappings
- What are roles
- What are permissions
- The configuration section (storing in token or metadata)
- API access

**Comment by angelaLazar** [comment]
https://github.com/auth0/docs/pull/2877

**Comment by sandrinodimattia** [comment]
Available here: https://auth0.com/docs/extensions/authorization-extension
