### ISSUE TITLE
Support pipeline v2 (API Authorization)

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#124]
In pipeline v2 the context exposes the `idToken` and `accessToken`. Our configuration should list options to store groups/roles/permissions in one of these tokens AND also allow you to define a custom attribute name (namespaced) for each property, like:

```
https://schemas.mycompany.com/groups
```

**Comment by twistedstream** [comment]
@sandrinodimattia: the workaround in the meantime is to create a downstream rule that sets the claims in the appropriate pipeline v2 places. Example:

```
context.accessToken.scope = user.permissions
```
