### ISSUE TITLE
Trying to determine api-key (for use in rules configuration settings)

### ISSUE THREAD

**Issue by iamjochem** [auth0/auth0-authorization-extension#129]
hi,

when installing the extension and it's rule script the following lines are generated (a snippet from the complete function/script):

```js
  // Get the policy for the user.
  function getPolicy(user, context, cb) {
    request.post({
      url: EXTENSION_URL + "/api/users/" + user.user_id + "/policy/" + context.clientID,
      headers: {
        "x-api-key": "4d38c7e0ba5f9844092cd589d22e2cc10d341226dd5d8fb1b6692531110aad61"
      },
      json: {
        connectionName: context.connection || user.identities[0].connection,
        groups: user.groups
      },
      timeout: 5000
    }, cb);
  }
``` 

I am trying to figure out a way to determine/retrieve the 'x-api-key' value for a given installation of without having to publish the generated rule (I have a custom variant of the script which I am trying to make "configuration based" so I can deploy the same script to different account") so that I can add a [global] rules-configuration setting.

is it possible to determine the correct api-key value without publishing the rule (and copy/pasting the relevant value from the generated script code)?

**Comment by mledom** [comment]
+1

**Comment by thameera** [comment]
Generally we recommend using the [resource server](https://auth0.com/docs/extensions/authorization-extension/v2/api-access) approach as it's more cleaner, but if you really need to determine the `x-api-key` without publishing the rule, you can follow these steps.

1. Find out the extension's EXTENSION_SECRET and Token.webtask_url using the command `wt inspect --profile "YOUR_PROFILE_NAME" --decrypt adf6e2f2b84784b57522e3b19dfc9201`
2. Use the algorithm in [this code snippet](https://github.com/auth0/auth0-authorization-extension/blob/545c6ab878ae715d4fe55e7e12d84f960634c6e0/server/plugins/auth.js#L10-L12) to generate the x-api-key. 

If you're not familiar with using `wt-cli` for the first step, the getting started instructions can be found under the tenant's [advanced settings](https://manage.auth0.com/#/tenant/webtasks).
