### ISSUE TITLE
The user picker should show the connection name

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#136]
There are cases where a user with the same email address and name might exist in multiple connections (eg: DB + AD). This is why we should have the following:

- [ ]  Show the connection name next to each user (both in the picker and in the overview)
- [ ] The filtering in the picker should be done based on the user_id and not on the email address

**Comment by zxan1285** [comment]
I added connection to the userPicker. 
Here how it looks:
![1](https://cloud.githubusercontent.com/assets/20518477/22587654/38a03fd2-ea0b-11e6-9831-a5cb34cec6ab.png)
In overview it was already done:
![2](https://cloud.githubusercontent.com/assets/20518477/22587660/3c4c7722-ea0b-11e6-8f79-4759d4465147.png)

And about filtering by user_id. Currently we using this 
`name:${input}* OR email.raw:${input}* OR user_metadata.name:${input}*`
as query. do you want me to replace this with `user_id:${input}`, or just add user_id as another option?
