### ISSUE TITLE
cosmetic issue: configuration switch status not properly displayed

### ISSUE THREAD

**Issue by rrexford** [auth0/auth0-authorization-extension#148]
1) Logout of tenant
2) Log-in to tenant
3) click authorization
4) go to configuration
5a) expected: switches are in the right state for rule configuration _previously_ saved
5b) actual: switches are all OFF
6) click on any other menu item
7) go back to configuration
8) switches are NOW in the right state

**Comment by sandrinodimattia** [comment]
This has been fixed in release 2.4
