### ISSUE TITLE
Feature Request: Update auth0 profile metadata when a user policy is updated

### ISSUE THREAD

**Issue by cmaftuleac** [auth0/auth0-authorization-extension#156]
It would be great if the user profile would be updated not only when the user logs in but also when someone makes changes in the Authorization Extension Dashboard.

In the flow that we are planing to use the extension an administrator might modify the User Permissions, but that wont be reflected in the /userinfo, and we dont want to bother user with re-login requests. Once the user is authenticated we plan to use very long token lifetime or refresh tokens.

As a workaround currently on the resource server I am forced to query the webtask /policy endpoint directly to get the updated metadata.

**Comment by sandrinodimattia** [comment]
This is not something we can implement as part of the extension. Imagine you have a group with 500 users in it and you assign a new role to that group. This would require use to update the metadata of all 500 users. If you have nested groups it can even get worse.

All of this would be handled through API calls for every user. This would be fine if we had a way to implement eventual consistency, but the extensions platform does not make this possible today (we don't have primitives like queues for example).
