### ISSUE TITLE
API / Token Exchange Broken?

### ISSUE THREAD

**Issue by NoCopy** [auth0/auth0-authorization-extension#167]
As of today Sept. 27 at around noon MST all API requests for the Authorization API return with a 401 - invalid token:

Using the flow directly from the dashboard under the API "Test" Tab

REQUEST FOR TOKEN EXCHANGE
```
curl --request POST \
  --url https://<DOMAIN>/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"<XXX>","client_secret":"<XXX>","audience":"urn:auth0-authz-api","grant_type":"client_credentials"}'
```

RESPONSE
```
{
  "access_token": "<APITOKEN>",
  "token_type": "Bearer"
}
```

GET /api/groups (or anything related to the authorization API)
```
{
    "statusCode": 401,
    "error": "Unauthorized",
    "message": "Invalid token",
    "attributes": {
        "error": "Invalid token"
    }
}
```

**Comment by Maxsky5** [comment]
Same problem here, every single request is returning a 401 - Invalid token.

It just stoped working this afternoon...

**Comment by DanielMarti** [comment]
Same here. 401 Unauthorized. It stopped working this morning. jwt.io says that the token has an 'Invalid Signature'.
