### ISSUE TITLE
Should set default applicationId when create new permission

### ISSUE THREAD

**Issue by ittus** [auth0/auth0-authorization-extension#181]
## Description

When create new permission, Application select is set default to first application, but after filling `name` and `description` and clicking `Create` button, receive error message:

Gif Image:
> Oh snap! An error occured while saving the permission: Permission with name "123" already exists for this application

![permission_error](https://user-images.githubusercontent.com/5120965/32212751-ad7be3ae-be5b-11e7-9172-50e4e4b34dd4.gif)

## Expected behaviours

applicationId should be set default to first application's id.

**Comment by Joker2000** [comment]
Same happening for me.

**Comment by LLihao** [comment]
Click on the application dropdown, and select an application. 
Seems like they default to a application for dropdown, but the `applicationid` is not submitted in the request.

**Comment by zacwolfe** [comment]
This is happening to me. I created 2 permissions successfully but now I'm getting that error
