### ISSUE TITLE
Extension not playing nicely with Extensions in the Auth0 dashboard

### ISSUE THREAD

**Issue by marcdavi-es** [auth0/auth0-authorization-extension#2]
Just experimenting with Auth0. 

Looks pretty awesome and I'm interested in how it can be extended to manage more granular permissions. 

This extension looks cool but I can't find it in the Extensions via the dashboard...

![screen shot 2016-05-09 at 17 47 47](https://cloud.githubusercontent.com/assets/8591501/15121293/d4a31a0e-1611-11e6-9c1e-5865c8453f54.png)

...and when I try to add it I get an Error message telling me it's already there...

![screen shot 2016-05-09 at 17 45 53](https://cloud.githubusercontent.com/assets/8591501/15121300/e39233b0-1611-11e6-90b3-5520e0809185.png)

I'm currently on the trial plan. I realise this may be an Auth0 user support thing rather than an issue but thought it was worth raising here.

Thanks :)

**Comment by sandrinodimattia** [comment]
The extension is currently only available for US accounts. We're working on making it available in EU and AU soon.
