### ISSUE TITLE
app_metadata not synchronising

### ISSUE THREAD

**Issue by eyeonx** [auth0/auth0-authorization-extension#203]
Hi guys, thank you for this extension!

I gave it a try, but when I assign a role to a user, the `app_metadata` field on the user profile object doesn't update.

I activated all switches on the configuration page.

Maybe I'm missing something, could you please help me?

**Comment by bradmkjr** [comment]
I've found it doesn't update app_metadate until the user logins. Thinking about what it would take to update the app_metadata for possibly hundreds of users for every small change to a role, permission or group would add a huge overhead to an already slow system.

**Comment by aarongodin** [comment]
What @bradmkjr said is accurate - you won't see the metadata updated until the user logs in (when the rule runs). Closing this as it seems like the question is answered but feel free to reply if that's not the case.
