### ISSUE TITLE
Cannot find module auth0-extension-hapi-tools@1.2.2

### ISSUE THREAD

**Issue by hastarin** [auth0/auth0-authorization-extension#212]
We've been using the extension just fine until today.

If I just hit try on the rule I'm getting an error:
`{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'auth0-extension-hapi-tools@1.2.2'",
  "error": "Cannot find module 'auth0-extension-hapi-tools@1.2.2'",
  "stack": "Error: Cannot find module 'auth0-extension-hapi-tools@1.2.2'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:49:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)\n    at require (/data/sandbox/lib/module.js:136:21)\n    at Object.module.exports.r (/data/io/2f66012c-629f-4dcd-916b-f5cc48f0dc0e/webtask.js:1:12690)\n    at t (/data/io/2f66012c-629f-4dcd-916b-f5cc48f0dc0e/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/2f66012c-629f-4dcd-916b-f5cc48f0dc0e/webtask.js:1:85556)\n    at t (/data/io/2f66012c-629f-4dcd-916b-f5cc48f0dc0e/webtask.js:1:177)\n    at /data/io/2f66012c-629f-4dcd-916b-f5cc48f0dc0e/webtask.js:1:560\n    at Object.<anonymous> (/data/io/2f66012c-629f-4dcd-916b-f5cc48f0dc0e/webtask.js:1:571)"
}`

I suspect this is related to the node.js changes?

**Comment by nenjotsu** [comment]
Same problem here

**Comment by vincentpun** [comment]
Same here. The auth extension was working fine until today. Entering the authorization extension page shows this error:

```
{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'auth0-extension-hapi-tools@1.2.2'",
  "error": "Cannot find module 'auth0-extension-hapi-tools@1.2.2'",
  "stack": "Error: Cannot find module 'auth0-extension-hapi-tools@1.2.2'\n    at Function.Module._resolveFilename (module.js:547:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:49:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)\n    at require (/data/sandbox/lib/module.js:136:21)\n    at Object.module.exports.r (/data/io/223199cd-8a72-4e6a-9b7b-fe4b8f1ea25d/webtask.js:1:12690)\n    at t (/data/io/223199cd-8a72-4e6a-9b7b-fe4b8f1ea25d/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/223199cd-8a72-4e6a-9b7b-fe4b8f1ea25d/webtask.js:1:85556)\n    at t (/data/io/223199cd-8a72-4e6a-9b7b-fe4b8f1ea25d/webtask.js:1:177)\n    at /data/io/223199cd-8a72-4e6a-9b7b-fe4b8f1ea25d/webtask.js:1:560\n    at Object.<anonymous> (/data/io/223199cd-8a72-4e6a-9b7b-fe4b8f1ea25d/webtask.js:1:571)"
}
```

**Comment by duhseekoh** [comment]
same here, not working at all. my production app is entirely offline.

**Comment by geonewlitho** [comment]
Same issue, this is critical (clients can't log-in).

According to [this link](https://auth0.com/docs/migrations/guides/extensibility-node8) they planned to 
> 2018 April 23: All official Auth0 Extensions will be updated to run on Node 8 and available for you to upgrade in the Installed Extensions tab of the Extensions page

Looks like something went wrong...

**Comment by seanvm** [comment]
Same problem here.....

**Comment by Karsone** [comment]
All of our production logins are down.

**Comment by duhseekoh** [comment]
@geonewlitho - and there is no option to upgrade, even if i wanted to:
![image](https://user-images.githubusercontent.com/931588/39164840-8cae02ba-474f-11e8-8872-039cea35d75e.png)

**Comment by geonewlitho** [comment]
@duhseekoh  Yes, same here

**Comment by lucasklaassen** [comment]
We have clients in the US and Australia that cannot login. I've tried deleting the extension to try and bypass this error but even that doesn't work. We are locked out of our production app!

```

{
  "code": 400,
  "message": "Compilation failed: Cannot find module 'auth0-extension-hapi-tools@1.2.2'",
  "error": "Cannot find module 'auth0-extension-hapi-tools@1.2.2'",
  "stack": "Error: Cannot find module 'auth0-extension-hapi-tools@1.2.2'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:49:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)\n    at require (/data/sandbox/lib/module.js:136:21)\n    at Object.module.exports.r (/data/io/82e9b154-5160-46b3-8a2b-2dc5c3ca65d8/webtask.js:1:12690)\n    at t (/data/io/82e9b154-5160-46b3-8a2b-2dc5c3ca65d8/webtask.js:1:177)\n    at Object.<anonymous> (/data/io/82e9b154-5160-46b3-8a2b-2dc5c3ca65d8/webtask.js:1:85556)\n    at t (/data/io/82e9b154-5160-46b3-8a2b-2dc5c3ca65d8/webtask.js:1:177)\n    at /data/io/82e9b154-5160-46b3-8a2b-2dc5c3ca65d8/webtask.js:1:560\n    at Object.<anonymous> (/data/io/82e9b154-5160-46b3-8a2b-2dc5c3ca65d8/webtask.js:1:571)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)\n    at /data/sandbox/lib/compiler.js:231:17\n    at /data/sandbox/node_modules/async/dist/async.js:3866:24\n    at replenish (/data/sandbox/node_modules/async/dist/async.js:998:17)"
}
```

**Comment by ramiljoaquin-ubidy** [comment]
All our system is not working.  Please help us.

**Comment by lucasklaassen** [comment]
<img width="523" alt="screen shot 2018-04-23 at 8 42 28 pm" src="https://user-images.githubusercontent.com/6452107/39164939-ddf06bc2-4736-11e8-97be-9f27d3c87887.png">

https://www.youtube.com/watch?v=FPzKWgt1qi8

**Comment by seanvm** [comment]
@fyockm PLS SEND HELP

**Comment by matchdav** [comment]
umm guys.  this is super awful.

**Comment by worixtech** [comment]
Same here!!!! Please help...

**Comment by duhseekoh** [comment]
https://twitter.com/auth0status/status/988627623780671488

**Comment by geonewlitho** [comment]
According to a user on the community forums, [auth0 is aware and working on a fix](https://community.auth0.com/t/authorization-extension-compilation-failed/11108/6).

**Comment by takahser** [comment]
+1

**Comment by sydney65** [comment]
Our production login has been down for 60 minutes and counting!

**Comment by seanvm** [comment]
`Investigating: We are investigating an increase in errors associated with Authz exetnsions.` - Looks like Authz is aware

**Comment by thehappycoder** [comment]
https://status.auth0.com/incidents/6sls0lhzrc4s

**Comment by hastarin** [comment]
@fyockm This would appear to be related to your latest commit?

**Comment by hastarin** [comment]
In my case the latest commit (rolling back the hapi-tools version) appears to have fixed it.  (AU tenant here)

**Comment by ronaksharma8** [comment]
It's working fine at my end too.

**Comment by worixtech** [comment]
It's working for me now!

**Comment by ramiljoaquin-ubidy** [comment]
Auth0 Status Update:
https://status.auth0.com/incidents/6sls0lhzrc4s
