### ISSUE TITLE
500 from Api

### ISSUE THREAD

**Issue by amits1995** [auth0/auth0-authorization-extension#221]
I got this 500 while GETing /groups:  
```
{ "code": 500, "error": "Script generated an unhandled asynchronous exception.", "details": "Error: Blocked event loop","name": "Error", "message": "Blocked event loop", "stack": "Error: Blocked event loop\n at <anonymous>:1:38\n at nextTickCallbackWith0Args (node.js:489:9)\n at process._tickDomainCallback (node.js:459:13)"}'
```
I think it's more of a webtask.io problem

**Comment by ShayMe21** [comment]
Is your tenant using Node 4 or Node 8? You can find out and change this in your Tenant [settings](https://manage.auth0.com/#/tenant/advanced). if you are using Node 8 make sure the Authorization extension is also using the Node 8 API, as the extension does not update the URL of the API when you change Node versions. This issue should no longer happen on Node 8.

You can regenerate the rule in Extension settings, to update the rule to use the new Node 8 URL. See this [comment](https://github.com/auth0/auth0-authorization-extension/issues/165#issuecomment-445960183) for details.

**Comment by amits1995** [comment]
We have since migrated to our own authorization solution since Auth0 support told us this extension is going to be deprecated and they won't fix our errors.  
Thx anyway
