### ISSUE TITLE
Feature Request: Publish API Key and Extension URL for authz rules script as rules-config Key-Value Pairs

### ISSUE THREAD

**Issue by tmertens** [auth0/auth0-authorization-extension#235]
When publishing a rule from the authorization extension (e.g. the `auth0-authorization-extension` Rule) to auth0, the Extension URL and API Key should be encoded as rules-config key value pairs.

Currently these values are directly encoded in the resulting rule script.  This is not desirable for multiple reasons:

1. The Key and URL are not configurable in a multi-tenant configuration without script modifications.
1. The API Key can be easily leaked by exporting configuration via the [auth0 deploy CLI](https://github.com/auth0/auth0-deploy-cli).
1. Custom modifications to the authz script to address the preceding points will be clobbered if a user redeploys the script via the authorization extension configuration page.

Instead, I propose encoding these as rules-config key-value pairs, for example `AUTHORIZATION_EXTENSION_URL` and `AUTHORIZATION_EXTENSION_API_KEY`

**Comment by fyockm** [comment]
Fixed by https://github.com/auth0/auth0-authorization-extension/pull/242
