### ISSUE TITLE
Role based security

### ISSUE THREAD

**Issue by davidjamesstone** [auth0/auth0-authorization-extension#244]
In the same way as we can control who is able to use the User Delegation extension via a well known role:

```
"app_metadata": {
    "roles": [
      "Delegated Admin - Administrator"
    ],
    ...
```

It would be nice to be able to do the same in the Authz extension.

**Comment by aarongodin** [comment]
Hey @davidjamesstone, we are not planning on any feature enhancements to the extension as it's in maintenance mode. We do have plans to add role-based access to Auth0's core platform, so in the future this would be an option using the core RBAC capabilities.
