### ISSUE TITLE
Is this extension still supported?

### ISSUE THREAD

**Issue by bsbechtel** [auth0/auth0-authorization-extension#245]
This repo hasn't been updated in some time, and a number of open issues and PRs are 6 months old or more. Is Auth0 planning on continuing to support and update the authorization extension, or should Auth0 customers look to migrate to another solution for authorization management?

**Comment by davidssonarnor** [comment]
Any feedback from the Auth0? We are starting a project using the extension.

**Comment by bsbechtel** [comment]
We have a call with them in the near future. I'll update you with whatever we learn. I would explore other options in the meantime, especially if you want to be able to scale your authorization solution to a large number of users.
