### ISSUE TITLE
Why is the extension checking for @clients in the token sub?

### ISSUE THREAD

**Issue by chillyistkult** [auth0/auth0-authorization-extension#250]
You check if the token sub ends with @clients here https://github.com/auth0/auth0-authorization-extension/blob/f5b09032bdeb2244c46c0818b69c9a89f415b5f3/server/plugins/auth.js#L87
Sadly when I follow the instructions on how to use the authorization-extension-api my access tokens always gets created with `@clients` in the end. I would like to know why this is happening and what is the reason for you to check for this case? Also I would suggest to change the error message from `Inavlid Token` to something that points to this issue as it took some time to figure out what is going on, because the token itself is valid.

**Comment by nicbavetta** [comment]
When a token's subject ends with "@clients", then the token was created through a Client Credentials grant and represents a Machine-to-Machine application.

I do not know the nature of the auth0-authorization-extension (I stumbled across this page through an unrelated search), however, perhaps you should be using a different grant flow to acquire your token?
