### ISSUE TITLE
Expand character limit for group name

### ISSUE THREAD

**Issue by charlesjohnson** [auth0/auth0-authorization-extension#255]
Submitted on behalf of @hghandri, who originally filed this into ProdPad:

 Regarding the group mapping on the Authorization extension, is it possible to increase number max of characters, it is limited to 15 characters, In my case the group name has more than 15 characters.

**Comment by aarongodin** [comment]
The groupName character limit for the mappings is 50 at the moment. Closing as we are not making feature enhancements to this extension.
