### ISSUE TITLE
Is there API support for this extension?

### ISSUE THREAD

**Issue by protege527** [auth0/auth0-authorization-extension#4]
It looks like users could be added to groups programmatically by adding the group to the user profile in the app_metadata section. Is it also possible to create groups via an API?

**Comment by sandrinodimattia** [comment]
Programmatic support will be added in the future. Now adding groups directly to the app_metadata section is not a good solution in this case because the rule that is generated will store the groups in the user profile after every login (effectively overwriting your data)
