### ISSUE TITLE
Create an API Explorer for the API Endpoints

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#89]
Investigate adding a new tab here with a Swagger API explorer:

![image](https://cloud.githubusercontent.com/assets/655409/20344475/359ac830-abf3-11e6-876c-7e3aa076d0df.png)

**Comment by sandrinodimattia** [comment]
https://github.com/glennjones/hapi-swagger

**Comment by sandrinodimattia** [comment]
These endpoints:

![image](https://cloud.githubusercontent.com/assets/655409/20405341/e8acf270-ad08-11e6-9006-322da27a9707.png)

**Comment by sericaia** [comment]
https://github.com/glennjones/hapi-swagger/blob/master/usageguide.md#json-without-ui

**Comment by sericaia** [comment]
https://github.com/auth0/auth0-authorization-extension/pull/117
