### ISSUE TITLE
Support S3 as a storage provider

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#90]
We currently use webtask storage to persist groups, roles and permissions. Support these additional providers to go beyond the storage limit.

**Comment by sandrinodimattia** [comment]
- [ ] Update webtask.json (similar to TFS)
- [ ] Use the S3 extension tools
- [ ] Testing

**Comment by aarongodin** [comment]
This has been implemented - closing.
