### ISSUE TITLE
Searching for data clears the query and also causes a strange flash in the page

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/auth0-authorization-extension#97]
Steps:

 1. Go to users
 2. Type "john"
 3. Press enter
 4. The list only shows users matching "john", but the word "john" is gone and any filter I have on the right (eg: User / Email / Connection) resets back to User

For Groups/Roles an additional thing happens when you press enter, the page becomes white for a second.

**Comment by sericaia** [comment]
Assign me to this one ;)

**Comment by sericaia** [comment]
https://github.com/auth0/auth0-authorization-extension/pull/102 w/ simple solution
